<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:datelist" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:datelist">
<types>
<xsd:schema targetNamespace="urn:datelist"
>
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
</xsd:schema>
</types>
<message name="getProdRequest">
  <part name="date" type="xsd:string" /></message>
<message name="getProdResponse">
  <part name="return" type="xsd:string" /></message>
<portType name="datelistPortType">
  <operation name="getProd">
    <documentation>Get closest date</documentation>
    <input message="tns:getProdRequest"/>
    <output message="tns:getProdResponse"/>
  </operation>
</portType>
<binding name="datelistBinding" type="tns:datelistPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="getProd">
    <soap:operation soapAction="urn:datelist#getProd" style="rpc"/>
    <input><soap:body use="encoded" namespace="urn:datelist" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
    <output><soap:body use="encoded" namespace="urn:datelist" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>
<service name="datelist">
  <port name="datelistPort" binding="tns:datelistBinding">
    <soap:address location="http://purple-comet-84-131808.euw1-2.nitrousbox.com/datelist.php"/>
  </port>
</service>
</definitions>